ALTER TABLE customers
    MODIFY COLUMN phone   VARCHAR(255) NULL,
    MODIFY COLUMN email   VARCHAR(255) NULL,
    MODIFY COLUMN address VARCHAR(255) NULL,
    MODIFY COLUMN city    VARCHAR(100) NULL,
    MODIFY COLUMN state   VARCHAR(2)   NULL;